
export const EXAM_DATA = 'EXAM_DATA';

export const MOVE_TO_NEXT_QUESTION = 'MOVE_TO_NEXT_QUESTION';
export const MOVE_TO_PREVIOUS_QUESTION = 'MOVE_TO_PREVIOUS_QUESTION';

export const SWITCH_EXAM_STATUS = 'SWITCH_EXAM_STATUS';