import { takeLatest, call, put, select } from 'redux-saga/effects';
import { shareImage } from '../actions/routines';
import { uploadImage } from '../api/apis';
import { FB_APPID } from '../config/config';

/* WORKER SAGA */
function* shareImageSaga(action) {
    try {
        const { userData } = yield select();
        // string generated by canvas.toDataURL()
        let form = yield new FormData();
        var image = yield new Image();
        yield image.src = action.payload;
        yield form.append('image', image.decode());
        console.log('dfdsf',form);
        let uploadResponse = yield call(uploadImage, form);
        console.log('uploaded', uploadResponse);
        yield put(shareImage.success());
    } catch (error) {
        console.log('error', error)
        yield put(shareImage.failure(error));
    }
}

/* WATCHER SAGA */
export default function* watchShareImage() {
    // run fetchDataFromServer on every trigger action
    yield takeLatest(shareImage.TRIGGER, shareImageSaga);
}
